# Generated by Django 6.0.7 on 2026-08-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('login_error', 'Sign-in Failed — Server Fault'), ('logout', 'Logout'), ('register', 'Registration Submitted'), ('approve_user', 'User Approved'), ('view_evidence', 'Evidence Viewed'), ('verify_evidence', 'Evidence Integrity Verified'), ('export_evidence', 'Evidence Exported'), ('analyse_session', 'Detection Run'), ('triage_detection', 'Finding Triaged'), ('issue_certificate', 'Section 63 Certificate Issued'), ('sign_certificate', 'Section 63 Part B Signed')], max_length=32),
        ),
    ]
