# Generated by Django 6.0.7 on 2026-08-20 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('investigator', 'Investigator'), ('expert', 'FSL / Examiner'), ('viewer', 'Viewer')], default='viewer', max_length=20),
        ),
    ]
