#!/usr/bin/env bash
#
# Fetch the real-world captures used to validate the detection engine.
#
# Everything else in the test corpus is synthetic — generated by the same
# codebase that analyses it, which proves only that the two agree with each
# other. These two captures come from malware-traffic-analysis.net with
# independently published ground truth, and running against them found five
# defects that the synthetic corpus could not (see
# research/96_REAL_TRAFFIC_VALIDATION.md).
#
# They are NOT committed: ~72 MB, and redistributing someone else's research
# corpus is not ours to do. This script pulls them on demand instead.
#
# The archives are password-protected because they sit alongside live malware
# samples on that site. The scheme is documented as an image on the site's
# about page (deliberately, to deter bulk scraping): the password is the word
# "infected", an underscore, and the post date as YYYYMMDD. The files fetched
# here are packet captures — inert data, not executables — but treat anything
# from that domain with the care its author asks for.
#
# Usage:  ./scripts/fetch_reference_captures.sh
#         python manage.py import_pcap reference_captures/<file> --name REAL-...
#         python manage.py analyze_session <id>

set -euo pipefail

DEST="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/reference_captures"
BASE="https://www.malware-traffic-analysis.net"
UA="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/126.0 Safari/537.36"

mkdir -p "$DEST"
cd "$DEST"

# date_path | archive name | expected pcap name
CAPTURES=(
  "2024/03/14|2024-03-14-AsyncRAT-and-XWorm-infection-traffic.pcap.zip|20240314"
  "2024/12/18|2024-12-18-one-week-of-server-scans-and-probes-and-web-traffic.pcap.zip|20241218"
)

for entry in "${CAPTURES[@]}"; do
  IFS='|' read -r datepath archive datestamp <<< "$entry"
  pcap="${archive%.zip}"

  if [[ -f "$pcap" ]]; then
    echo "already present: $pcap"
    continue
  fi

  echo "fetching $archive …"
  curl -fsSL -A "$UA" --max-time 300 "$BASE/$datepath/$archive" -o "$archive"

  # -o overwrite, -P password; the pcap is inert data, the zip is not executed
  unzip -o -P "infected_${datestamp}" "$archive" >/dev/null
  rm -f "$archive"
  echo "  -> $pcap"
done

echo
echo "Reference captures in $DEST:"
ls -la "$DEST"/*.pcap
cat <<'NOTE'

Ground truth for the AsyncRAT capture (from the author's published notes):
  C2: 91.134.150.150:3232, 91.92.252.234:3232, 91.134.150.150:7000

The server capture is one week of a real internet-facing host being scanned;
use it as the false-positive test. Its addresses are public, so the default
RFC 1918 HOME_NET is wrong for it:
  HOME_NET="203.161.44.0/24" python manage.py analyze_session <id>
NOTE
