"""
Django settings for netforensiq_backend project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import os
import secrets
from datetime import timedelta

from dotenv import load_dotenv

load_dotenv(os.path.join(Path(__file__).resolve().parent.parent, '.env'))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# A generated ephemeral key keeps a fresh clone runnable; any real deployment
# must set SECRET_KEY in .env, otherwise sessions and tokens reset on restart.
SECRET_KEY = os.getenv('SECRET_KEY') or secrets.token_urlsafe(50)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# Every other setting in this file reads the environment; this one was the
# exception, which meant the platform could not be deployed to any hostname
# without editing source. Comma-separated.
ALLOWED_HOSTS = [
    host.strip() for host in os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'accounts',
    'capture',
    'evidence',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'netforensiq_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'netforensiq_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# PostgreSQL when DB_NAME is configured; SQLite otherwise.
# The fallback exists so a demo or review machine can run the full stack with
# no database server installed — capture, detection and evidence export all
# work on SQLite. PostgreSQL remains the deployment target.
if os.getenv('DB_NAME'):
    DATABASES = {
        'default': {
            'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.postgresql'),
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            # Overridable so a clean-start check, or a second demo dataset, can
            # run without clobbering the database you have been working in.
            'NAME': os.getenv('SQLITE_NAME') or (BASE_DIR / 'netforensiq.sqlite3'),
        }
    }


# Cache
#
# This is not incidental configuration: DRF's throttling stores its counters
# here, so the cache backend decides whether the login rate limit is real.
#
# Django's default is LocMemCache, which is per-process. Under it:
#   * every worker keeps its own counter, so a limit of 8/hour becomes
#     8 x (number of workers) against the deployment as a whole;
#   * all throttle state is lost on restart, so a brute-force attempt is
#     cleared by any deploy or crash.
#
# A file-based cache is shared between processes and survives restarts, which
# is the least a rate limit has to do to mean anything. Point CACHE_LOCATION
# at a Redis/Memcached URL in a real deployment.
CACHES = {
    'default': {
        'BACKEND': os.getenv(
            'CACHE_BACKEND', 'django.core.cache.backends.filebased.FileBasedCache',
        ),
        'LOCATION': os.getenv('CACHE_LOCATION', str(BASE_DIR / '.cache')),
    }
}

# The test suite gets its own cache directory.
#
# Without this the runner shares backend/.cache with the dev server, so the
# login throttle carries counters across the boundary: run the app, then run
# `manage.py test`, and 27 tests fail on a 429 that has nothing to do with the
# code under test. verify.sh worked around it by clearing the cache first,
# which left the documented command failing while the harness passed.
#
# The runner still uses the *file-based* backend, not LocMemCache, so the
# throttle tests exercise the same shared-counter behaviour as a deployment.
TEST_RUNNER = 'netforensiq_backend.test_runner.IsolatedCacheRunner'


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Storage is UTC and stays UTC: a capture timestamp has to mean the same
# instant regardless of where the file is opened, and daylight rules must
# never touch an evidential time. Presentation converts — the Section 63
# certificate renders IST because the statutory form's field is labelled
# "Time (IST)", and the UI labels whichever zone it displays.
TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Evidence storage. Ingested PCAPs are copied here and never modified; hashes
# are computed on arrival and re-verified on every export.
MEDIA_ROOT = Path(os.getenv('MEDIA_ROOT', BASE_DIR / 'evidence_store'))
MEDIA_URL = 'media/'
EVIDENCE_ROOT = MEDIA_ROOT / 'pcaps'
CERTIFICATE_ROOT = MEDIA_ROOT / 'certificates'

# The address space being investigated, in the sense Snort and Suricata use
# $HOME_NET. Egress rules (C2 beaconing, covert channels) only fire when the
# initiator is inside it — otherwise every scanner on the internet reaching in
# is reported as an internal host calling out.
#
# The default suits the common case: a capture taken inside an office or
# suspect network, where hosts are RFC 1918. It is WRONG for a capture of a
# public-facing server, whose own addresses are public — set HOME_NET
# explicitly for those, e.g. HOME_NET=203.0.113.0/24,198.51.100.0/24
HOME_NET = [
    entry.strip() for entry in os.getenv(
        'HOME_NET', '10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,fd00::/8',
    ).split(',') if entry.strip()
]

# Vite's default dev port. Both loopback spellings are listed because the
# browser treats localhost and 127.0.0.1 as distinct origins.
#
# The Playwright port used to be baked in here as well, which meant the test
# harness's origin shipped in the deployed allowlist. It is supplied by the
# harness through CORS_EXTRA_ORIGINS instead, so nothing test-only reaches a
# deployment that does not ask for it.
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]
_extra_origins = os.getenv('CORS_EXTRA_ORIGINS', '')
if _extra_origins:
    CORS_ALLOWED_ORIGINS += [o.strip() for o in _extra_origins.split(',') if o.strip()]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # Deny by default. Endpoints that must be public opt out explicitly with
    # permission_classes = [AllowAny]; nothing is exposed by forgetting to set it.
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '30/hour',
        'user': '1000/hour',
        'login': '8/hour',
        # Enrolment writes rows to the user table from unauthenticated input.
        # A flooded approval queue is a denial of service against the
        # administrator who has to work through it, not just against the server.
        'register': '5/hour',
        # Public by necessity — an applicant has no account to sign in with —
        # so it is limited by volume rather than by identity.
        'approval_status': '20/hour',
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

AUTH_USER_MODEL = 'accounts.User'


# Exhibit and certificate identifier prefixes.
#
# "NF-2026…" and "S63-2026…" are this project's scheme. A unit with its own
# exhibit numbering — which most have — sets these rather than accepting ours
# on documents that go into a case file.
EXHIBIT_PREFIX = os.getenv('EXHIBIT_PREFIX', 'NF')
CERTIFICATE_PREFIX = os.getenv('CERTIFICATE_PREFIX', 'S63')

# Shown on the Section 63 certificate as the issuing body. Blank prints
# nothing rather than inventing an organisation.
ISSUING_ORGANISATION = os.getenv('ISSUING_ORGANISATION', '')
