# Generated by Django 6.0.7 on 2026-08-15 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capture', '0003_detection_review_note_detection_reviewed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exhibit_number', models.CharField(max_length=100, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_path', models.CharField(max_length=500)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('sha256_hash', models.CharField(db_index=True, max_length=64)),
                ('md5_hash', models.CharField(blank=True, max_length=32)),
                ('hash_algorithm_declared', models.CharField(choices=[('SHA256', 'SHA256'), ('SHA1', 'SHA1'), ('MD5', 'MD5'), ('Other', 'Other (Legally acceptable standard)')], default='SHA256', max_length=10)),
                ('status', models.CharField(choices=[('sealed', 'Sealed — hash verified'), ('tampered', 'Integrity check FAILED'), ('archived', 'Archived')], default='sealed', max_length=12)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('acquisition_timestamp', models.DateTimeField()),
                ('device_type', models.CharField(choices=[('computer', 'Computer/Storage Media'), ('dvr', 'DVR'), ('mobile', 'Mobile'), ('flash', 'Flash Drive'), ('cd_dvd', 'CD/DVD'), ('server', 'Server'), ('cloud', 'Cloud'), ('other', 'Other')], default='computer', max_length=12)),
                ('device_make_model', models.CharField(blank=True, max_length=200)),
                ('device_serial', models.CharField(blank=True, max_length=120)),
                ('device_identifier', models.CharField(blank=True, help_text='IMEI/UIN/UID/MAC/Cloud ID, as applicable', max_length=200)),
                ('custodian_relationship', models.CharField(choices=[('owned', 'Owned'), ('maintained', 'Maintained'), ('managed', 'Managed'), ('operated', 'Operated')], default='operated', max_length=12)),
                ('case_reference', models.CharField(blank=True, max_length=120)),
                ('seized_from', models.CharField(blank=True, max_length=200)),
                ('acquisition_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Section63Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('part_a_name', models.CharField(blank=True, max_length=200)),
                ('part_a_designation', models.CharField(blank=True, max_length=200)),
                ('part_a_organisation', models.CharField(blank=True, max_length=200)),
                ('part_a_address', models.TextField(blank=True)),
                ('part_a_relationship', models.CharField(choices=[('owned', 'Owned'), ('maintained', 'Maintained'), ('managed', 'Managed'), ('operated', 'Operated')], default='operated', max_length=12)),
                ('part_a_signed_at', models.DateTimeField(blank=True, null=True)),
                ('part_b_name', models.CharField(blank=True, max_length=200)),
                ('part_b_designation', models.CharField(blank=True, max_length=200)),
                ('part_b_organisation', models.CharField(blank=True, max_length=200)),
                ('part_b_qualification', models.CharField(blank=True, help_text="s.63 does not define 'expert'; qualification is recorded so the court can assess competence.", max_length=300)),
                ('part_b_signed_at', models.DateTimeField(blank=True, null=True)),
                ('certified_sha256', models.CharField(max_length=64)),
                ('certified_md5', models.CharField(blank=True, max_length=32)),
                ('certified_algorithm', models.CharField(choices=[('SHA256', 'SHA256'), ('SHA1', 'SHA1'), ('MD5', 'MD5'), ('Other', 'Other (Legally acceptable standard)')], default='SHA256', max_length=10)),
                ('device_description', models.TextField(blank=True)),
                ('findings_summary', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_path', models.CharField(blank=True, max_length=500)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='evidence.evidencerecord')),
                ('part_a_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_a_certificates', to=settings.AUTH_USER_MODEL)),
                ('part_b_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_b_certificates', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='capture.capturesession')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='CustodyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('acquired', 'Acquired / Seized'), ('hashed', 'Hash computed'), ('verified', 'Integrity verified'), ('analysed', 'Analysed'), ('viewed', 'Viewed'), ('exported', 'Exported'), ('transferred', 'Custody transferred'), ('certificate', 'Section 63 certificate issued')], max_length=16)),
                ('actor_badge', models.CharField(blank=True, max_length=50)),
                ('actor_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('detail', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('previous_hash', models.CharField(blank=True, max_length=64)),
                ('entry_hash', models.CharField(blank=True, max_length=64)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_events', to=settings.AUTH_USER_MODEL)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custody_events', to='evidence.evidencerecord')),
            ],
            options={
                'ordering': ['evidence', 'sequence'],
                'unique_together': {('evidence', 'sequence')},
            },
        ),
    ]
