# Generated by Django 6.0.7 on 2026-08-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_alter_custodyevent_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencerecord',
            name='provenance',
            field=models.CharField(choices=[('seized', 'Seized — captured from a network under investigation'), ('reference', 'Reference — real traffic from a published corpus'), ('synthetic', 'SYNTHETIC — generated by this tool, not evidence'), ('unattested', 'Unattested — origin not declared')], default='unattested', max_length=12),
        ),
        migrations.AddField(
            model_name='evidencerecord',
            name='provenance_detail',
            field=models.TextField(blank=True),
        ),
    ]
