# Generated by Django 6.0.7 on 2026-08-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0003_evidencerecord_provenance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencerecord',
            name='sha1_hash',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='section63certificate',
            name='certified_sha1',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
