# Generated by Django 6.0.7 on 2026-08-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0004_evidencerecord_sha1_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencerecord',
            name='fir_number',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='evidencerecord',
            name='police_station',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
