# Generated by Django 6.0.7 on 2026-08-19 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0005_evidencerecord_fir_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='custodyevent',
            name='action',
            field=models.CharField(choices=[('acquired', 'Acquired / Seized'), ('hashed', 'Hash computed'), ('verified', 'Integrity verified'), ('analysed', 'Analysed'), ('viewed', 'Viewed'), ('exported', 'Exported'), ('transferred', 'Custody transferred'), ('certificate', 'Section 63 certificate issued'), ('part_b_signed', 'Section 63 Part B countersigned by expert'), ('case_linked', 'Linked to case')], max_length=16),
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('fir_number', models.CharField(blank=True, max_length=60)),
                ('police_station', models.CharField(max_length=200)),
                ('district', models.CharField(blank=True, max_length=120)),
                ('offence_sections', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('registered', 'FIR registered'), ('investigation', 'Under investigation'), ('chargesheeted', 'Report filed under BNSS s.193'), ('closed', 'Closed')], default='registered', max_length=16)),
                ('opened_on', models.DateField()),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_created', to=settings.AUTH_USER_MODEL)),
                ('investigating_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_as_io', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opened_on', '-id'],
            },
        ),
        migrations.AddField(
            model_name='evidencerecord',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exhibits', to='evidence.case'),
        ),
        migrations.CreateModel(
            name='CaseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('io', 'Investigating Officer'), ('expert', 'FSL / Examiner'), ('supervisor', 'Supervising Officer'), ('observer', 'Observer (read-only)')], max_length=12)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='evidence.case')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['case', 'role', 'id'],
                'unique_together': {('case', 'officer')},
            },
        ),
    ]
