# Generated by Django 6.0.7 on 2026-08-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0006_alter_custodyevent_action_case_evidencerecord_case_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencerecord',
            name='encrypted_at_rest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evidencerecord',
            name='encryption_algorithm',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
