# Generated by Django 6.0.7 on 2026-08-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0007_evidencerecord_encrypted_at_rest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custodyevent',
            name='action',
            field=models.CharField(choices=[('acquired', 'Acquired / Seized'), ('hashed', 'Hash computed'), ('verified', 'Integrity verified'), ('analysed', 'Analysed'), ('viewed', 'Viewed'), ('exported', 'Exported'), ('transferred', 'Custody transferred'), ('certificate', 'Section 63 certificate issued'), ('part_b_signed', 'Section 63 Part B countersigned by expert'), ('case_linked', 'Linked to case'), ('encrypted', 'Encrypted at rest')], max_length=16),
        ),
    ]
