# Generated by Django 6.0.7 on 2026-08-08 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('source_type', models.CharField(choices=[('live', 'Live Interface'), ('pcap', 'Imported PCAP')], max_length=10)),
                ('interface', models.CharField(blank=True, max_length=200)),
                ('pcap_filename', models.CharField(blank=True, max_length=255)),
                ('bpf_filter', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=12)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('packet_count', models.BigIntegerField(default=0)),
                ('byte_count', models.BigIntegerField(default=0)),
                ('flow_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capture_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_ip', models.GenericIPAddressField()),
                ('dst_ip', models.GenericIPAddressField()),
                ('src_port', models.IntegerField(default=0)),
                ('dst_port', models.IntegerField(default=0)),
                ('protocol', models.CharField(max_length=12)),
                ('packets_sent', models.IntegerField(default=0)),
                ('packets_received', models.IntegerField(default=0)),
                ('bytes_sent', models.BigIntegerField(default=0)),
                ('bytes_received', models.BigIntegerField(default=0)),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('avg_packet_size', models.FloatField(default=0.0)),
                ('packets_per_second', models.FloatField(default=0.0)),
                ('bytes_ratio', models.FloatField(default=0.0)),
                ('unique_dst_ports', models.IntegerField(default=1)),
                ('payload_entropy', models.FloatField(default=0.0)),
                ('tcp_flags_seen', models.CharField(blank=True, max_length=40)),
                ('app_protocol', models.CharField(blank=True, max_length=20)),
                ('dns_query_count', models.IntegerField(default=0)),
                ('longest_dns_label', models.IntegerField(default=0)),
                ('http_host', models.CharField(blank=True, max_length=255)),
                ('tls_sni', models.CharField(blank=True, max_length=255)),
                ('ja3_hash', models.CharField(blank=True, max_length=64)),
                ('is_analyzed', models.BooleanField(default=False)),
                ('anomaly_score', models.FloatField(blank=True, null=True)),
                ('risk_score', models.IntegerField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='capture.capturesession')),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='DNSRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_ip', models.GenericIPAddressField()),
                ('query_name', models.CharField(max_length=512)),
                ('query_type', models.CharField(blank=True, max_length=12)),
                ('response_ip', models.CharField(blank=True, max_length=64)),
                ('subdomain_length', models.IntegerField(default=0)),
                ('label_count', models.IntegerField(default=0)),
                ('query_entropy', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dns_records', to='capture.capturesession')),
                ('flow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dns_records', to='capture.flow')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='flow',
            index=models.Index(fields=['src_ip'], name='capture_flo_src_ip_19fad3_idx'),
        ),
        migrations.AddIndex(
            model_name='flow',
            index=models.Index(fields=['dst_ip'], name='capture_flo_dst_ip_bf84e6_idx'),
        ),
        migrations.AddIndex(
            model_name='flow',
            index=models.Index(fields=['session', 'last_seen'], name='capture_flo_session_9b288c_idx'),
        ),
        migrations.AddIndex(
            model_name='flow',
            index=models.Index(fields=['risk_score'], name='capture_flo_risk_sc_07fa71_idx'),
        ),
        migrations.AddIndex(
            model_name='dnsrecord',
            index=models.Index(fields=['session', 'timestamp'], name='capture_dns_session_e5c7ca_idx'),
        ),
    ]
