# Generated by Django 6.0.7 on 2026-08-15 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturesession',
            name='capture_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capturesession',
            name='capture_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flow',
            name='initiator_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flow',
            name='initiator_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flow',
            name='initiator_port',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flow',
            name='interval_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flow',
            name='interval_dispersion',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='flow',
            name='interval_mad',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='flow',
            name='interval_mean',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='flow',
            name='interval_median',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='flow',
            name='interval_stddev',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='flow',
            name='max_dns_entropy',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=40)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('method', models.CharField(choices=[('rule', 'Deterministic rule'), ('model', 'Unsupervised model')], default='rule', max_length=10)),
                ('confidence', models.FloatField(default=0.0)),
                ('rationale', models.TextField()),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('subject_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='capture.flow')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='capture.capturesession')),
            ],
            options={
                'ordering': ['-severity', '-confidence'],
                'indexes': [models.Index(fields=['session', 'severity'], name='capture_det_session_5d90c1_idx'), models.Index(fields=['rule_id'], name='capture_det_rule_id_85dad5_idx'), models.Index(fields=['subject_ip'], name='capture_det_subject_b19ae9_idx')],
            },
        ),
    ]
