# Generated by Django 6.0.7 on 2026-08-15 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0002_capturesession_capture_end_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='detection',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detection',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_detections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detection',
            name='triage_status',
            field=models.CharField(choices=[('new', 'Awaiting review'), ('confirmed', 'Confirmed by analyst'), ('dismissed', 'Dismissed — false positive'), ('escalated', 'Escalated')], db_index=True, default='new', max_length=12),
        ),
    ]
