# Generated by Django 6.0.7 on 2026-08-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0003_detection_review_note_detection_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detection',
            options={'ordering': ['-severity_rank', '-confidence']},
        ),
        migrations.RemoveIndex(
            model_name='detection',
            name='capture_det_session_5d90c1_idx',
        ),
        migrations.RemoveIndex(
            model_name='detection',
            name='capture_det_rule_id_85dad5_idx',
        ),
        migrations.RemoveIndex(
            model_name='detection',
            name='capture_det_subject_b19ae9_idx',
        ),
        migrations.AddField(
            model_name='detection',
            name='severity_rank',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Numeric rank of severity, so ordering is by urgency rather than by the alphabet.'),
        ),
    ]
