# Generated by Django 6.0.7 on 2026-08-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0004_alter_detection_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturesession',
            name='home_net',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
