# Generated by Django 6.0.7 on 2026-08-18 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0005_capturesession_home_net'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flow',
            name='anomaly_score',
        ),
        migrations.RemoveField(
            model_name='flow',
            name='ja3_hash',
        ),
        migrations.AddField(
            model_name='flow',
            name='ja4_fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='flow',
            name='ja4_raw',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dnsrecord',
            name='response_ip',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
