# Generated by Django 6.0.7 on 2026-08-18 10:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0006_remove_flow_anomaly_score_remove_flow_ja3_hash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='entropy_sample_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['session', 'severity'], name='capture_det_session_5d90c1_idx'),
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['rule_id'], name='capture_det_rule_id_85dad5_idx'),
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['subject_ip'], name='capture_det_subject_b19ae9_idx'),
        ),
    ]
