# Generated by Django 6.0.7 on 2026-08-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0007_flow_entropy_sample_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='app_protocol_source',
            field=models.CharField(blank=True, choices=[('observed', 'Observed in the payload'), ('port', 'Inferred from the port number')], max_length=10),
        ),
    ]
