# Generated by Django 6.0.7 on 2026-08-18 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0008_flow_app_protocol_source'),
        ('evidence', '0003_evidencerecord_provenance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturesession',
            name='evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='evidence.evidencerecord'),
        ),
    ]
