# Generated by Django 6.0.7 on 2026-08-19 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0010_link_sessions_to_exhibits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IOCFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('source', models.CharField(blank=True, max_length=500)),
                ('fmt', models.CharField(choices=[('feodo_ip', 'abuse.ch Feodo Tracker — IP blocklist CSV'), ('urlhaus', 'abuse.ch URLhaus — URL CSV'), ('plain_ip', 'Plain list — one address per line'), ('plain_domain', 'Plain list — one domain per line')], max_length=20)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_sha256', models.CharField(max_length=64)),
                ('file_bytes', models.BigIntegerField(default=0)),
                ('retrieved_on', models.DateField()),
                ('published_on', models.DateTimeField(blank=True, null=True)),
                ('licence', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('entry_count', models.IntegerField(default=0)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ioc_feeds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-retrieved_on', '-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='IOCIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ipv4', 'IPv4 address'), ('ipv6', 'IPv6 address'), ('domain', 'Domain name'), ('url', 'URL')], max_length=10)),
                ('value', models.CharField(max_length=512)),
                ('context', models.CharField(blank=True, max_length=300)),
                ('listed_on', models.DateTimeField(blank=True, null=True)),
                ('source_line', models.TextField(blank=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='capture.iocfeed')),
            ],
            options={
                'indexes': [models.Index(fields=['kind', 'value'], name='capture_ioc_kind_8fbe8b_idx')],
                'unique_together': {('feed', 'kind', 'value')},
            },
        ),
    ]
