# Generated by Django 6.0.7 on 2026-08-20 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0011_iocfeed_iocindicator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveMonitorState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('running', models.BooleanField(default=False)),
                ('stop_requested', models.BooleanField(default=False)),
                ('interface', models.CharField(blank=True, max_length=64)),
                ('window_seconds', models.PositiveIntegerField(default=30)),
                ('home_net', models.CharField(blank=True, max_length=200)),
                ('bpf_filter', models.CharField(blank=True, max_length=200)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_window_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('windows', models.PositiveIntegerField(default=0)),
                ('packets', models.BigIntegerField(default=0)),
                ('flows', models.PositiveIntegerField(default=0)),
                ('findings_total', models.PositiveIntegerField(default=0)),
                ('findings_new_total', models.PositiveIntegerField(default=0)),
                ('alerts_attempted', models.PositiveIntegerField(default=0)),
                ('alerts_delivered', models.PositiveIntegerField(default=0)),
                ('recent', models.JSONField(blank=True, default=list)),
                ('newest_findings', models.JSONField(blank=True, default=list)),
                ('deliveries', models.JSONField(blank=True, default=list)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='capture.capturesession')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'live monitor state',
                'verbose_name_plural': 'live monitor state',
            },
        ),
    ]
