"""
Encryption of the evidence store at rest.

The thing this must not break
-----------------------------
A Section 63 certificate asserts the SHA-256 of the capture as seized. That
digest is of the *plaintext*, and it has to stay true after this file exists.
So the sealed copy is encrypted, and everything that reads it — verification,
analysis, export — decrypts first and hashes what it gets. The number on the
certificate never becomes a digest of ciphertext, because a digest nobody
outside this system can reproduce is not evidence of anything.

Construction
------------
AES-256-GCM in 1 MiB chunks, each chunk with its own nonce and authentication
tag. Chunked rather than whole-file for a boring reason: a 500 MB capture
encrypted in one AESGCM call is a 500 MB bytes object in memory, and the
upload path already accepts files that size.

  header:  MAGIC (8 bytes) || nonce prefix (8 random bytes)
  chunk i: AES-256-GCM(nonce = prefix || counter, aad = MAGIC || counter)

The final chunk's counter carries a high bit that no other chunk carries. That
is what makes truncation detectable: lopping bytes off the end of the file
leaves a plaintext whose last chunk is not marked final, and decryption fails
rather than silently returning a shorter capture.

What this is and is not
-----------------------
It protects the evidence store against someone who obtains the disk or a
backup of it. It does not protect against someone who has the running system
and the key, and it is not a substitute for full-disk encryption on the
workstation — LUKS covers the database, the logs and the temporary files this
module writes while decrypting, none of which are in scope here.

If no key is configured the store is written in the clear and the system says
so, on the status page and in this module's `describe()`. Claiming encryption
that is not switched on would be worse than not having it.

Losing the key destroys the evidence. There is no recovery path and there is
not supposed to be one; that is what makes the encryption meaningful. Whoever
deploys this has to escrow the key somewhere other than the machine it
protects.
"""

import base64
import os
import struct
import tempfile
from contextlib import contextmanager
from pathlib import Path

from django.conf import settings

from cryptography.exceptions import InvalidTag
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

MAGIC = b'NFENCv1\x00'
KEY_BYTES = 32              # AES-256
NONCE_PREFIX_BYTES = 8
COUNTER_BYTES = 4
CHUNK_BYTES = 1024 * 1024
TAG_BYTES = 16
FINAL_FLAG = 0x80000000

ALGORITHM = 'AES-256-GCM (chunked, 1 MiB)'


class EvidenceDecryptionError(Exception):
    """Raised when a sealed artefact will not decrypt or fails its tag check."""


def _nonce(prefix, counter, final):
    return prefix + struct.pack('>I', counter | (FINAL_FLAG if final else 0))


def _aad(counter, final):
    return MAGIC + struct.pack('>I', counter | (FINAL_FLAG if final else 0))


# ── key handling ───────────────────────────────────────────────────────────

def _key_file():
    return Path(getattr(settings, 'EVIDENCE_KEY_FILE',
                        Path(settings.BASE_DIR) / '.evidence.key'))


def encryption_enabled():
    return str(getattr(settings, 'EVIDENCE_ENCRYPTION', 'on')).lower() != 'off'


def load_key(create=False):
    """
    The store key, or None when encryption is switched off or unavailable.

    Order: an explicit setting (so a deployment can hold the key in a secrets
    manager and never write it to disk), then the key file. `create=True` will
    generate the key file, which happens on first ingest rather than at import
    time — a key generated by merely importing a module is a key that gets
    generated by running the test suite.
    """
    if not encryption_enabled():
        return None

    configured = getattr(settings, 'EVIDENCE_ENCRYPTION_KEY', '') or os.getenv(
        'EVIDENCE_ENCRYPTION_KEY', '')
    if configured:
        key = base64.b64decode(configured)
        if len(key) != KEY_BYTES:
            raise ValueError(
                f'EVIDENCE_ENCRYPTION_KEY must decode to {KEY_BYTES} bytes, '
                f'got {len(key)}.'
            )
        return key

    path = _key_file()
    if path.exists():
        key = base64.b64decode(path.read_text().strip())
        if len(key) != KEY_BYTES:
            raise ValueError(f'{path} does not contain a {KEY_BYTES}-byte key.')
        return key

    if not create:
        return None

    key = AESGCM.generate_key(bit_length=256)
    # Written 0600 from the moment it exists, not chmod'ed afterwards — the
    # window between create and chmod is the whole vulnerability.
    handle = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    with os.fdopen(handle, 'w') as fh:
        fh.write(base64.b64encode(key).decode())
    return key


def describe():
    """
    The state of at-rest encryption, for the status page and the report.

    Never raises: a status endpoint that 500s because it could not read a key
    file tells the operator nothing about the thing they asked about.
    """
    if not encryption_enabled():
        return {
            'enabled': False,
            'algorithm': None,
            'reason': 'Disabled by configuration (EVIDENCE_ENCRYPTION=off).',
            'key_source': None,
        }
    try:
        key = load_key(create=False)
    except (ValueError, OSError) as exc:
        return {
            'enabled': False, 'algorithm': None,
            'reason': f'A key is configured but could not be read: {exc}',
            'key_source': None,
        }

    if key is None:
        return {
            'enabled': False,
            'algorithm': None,
            'reason': (
                'No key has been generated yet. The evidence store is written '
                'in the clear; the control in force is whatever full-disk '
                'encryption the workstation provides.'
            ),
            'key_source': None,
        }

    source = ('setting or environment'
              if (getattr(settings, 'EVIDENCE_ENCRYPTION_KEY', '')
                  or os.getenv('EVIDENCE_ENCRYPTION_KEY'))
              else str(_key_file()))
    return {
        'enabled': True,
        'algorithm': ALGORITHM,
        'reason': 'Sealed artefacts are encrypted before they touch the disk.',
        'key_source': source,
    }


# ── file operations ────────────────────────────────────────────────────────

def is_encrypted(path):
    """True when the file carries our header. Cheap enough to call per read."""
    try:
        with open(path, 'rb') as fh:
            return fh.read(len(MAGIC)) == MAGIC
    except OSError:
        return False


def encrypt_file(source, destination, key):
    """Write an encrypted copy of `source` to `destination`."""
    aes = AESGCM(key)
    prefix = os.urandom(NONCE_PREFIX_BYTES)

    with open(source, 'rb') as plain, open(destination, 'wb') as out:
        out.write(MAGIC)
        out.write(prefix)
        counter = 0
        chunk = plain.read(CHUNK_BYTES)
        while True:
            nxt = plain.read(CHUNK_BYTES)
            final = not nxt
            out.write(aes.encrypt(_nonce(prefix, counter, final), chunk,
                                  _aad(counter, final)))
            if final:
                break
            chunk, counter = nxt, counter + 1
    return destination


def decrypt_file(source, destination, key):
    """
    Write the plaintext of `source` to `destination`.

    Raises EvidenceDecryptionError on a wrong key, a corrupted chunk or a
    truncated file. It does not fall back to treating the bytes as plaintext:
    an artefact that will not decrypt is an incident, not a formatting quirk.
    """
    aes = AESGCM(key)
    encrypted = CHUNK_BYTES + TAG_BYTES

    with open(source, 'rb') as sealed, open(destination, 'wb') as out:
        if sealed.read(len(MAGIC)) != MAGIC:
            raise EvidenceDecryptionError(f'{source} is not an encrypted artefact.')
        prefix = sealed.read(NONCE_PREFIX_BYTES)
        if len(prefix) != NONCE_PREFIX_BYTES:
            raise EvidenceDecryptionError(f'{source} has a truncated header.')

        counter = 0
        block = sealed.read(encrypted)
        while block:
            nxt = sealed.read(encrypted)
            final = not nxt
            try:
                out.write(aes.decrypt(_nonce(prefix, counter, final), block,
                                      _aad(counter, final)))
            except InvalidTag as exc:
                raise EvidenceDecryptionError(
                    f'{source}: chunk {counter} failed its authentication tag. '
                    f'The key is wrong, or the file has been altered or truncated.'
                ) from exc
            if final:
                break
            block, counter = nxt, counter + 1
    return destination


@contextmanager
def readable(path):
    """
    Yield a path whose bytes are the capture as seized.

    Plaintext artefacts are handed back untouched — no copy, no temp file — so
    a store that was never encrypted costs nothing to read. Encrypted ones are
    decrypted into a 0600 temporary file that is removed on the way out,
    including when the caller raises.

    The temporary file is the weak point and it is worth naming: while an
    exhibit is being analysed its plaintext exists on disk. That is the reason
    the module docstring insists on full-disk encryption underneath this.
    """
    path = Path(path)
    if not is_encrypted(path):
        yield path
        return

    key = load_key(create=False)
    if key is None:
        raise EvidenceDecryptionError(
            f'{path} is encrypted but no key is configured. Set '
            f'EVIDENCE_ENCRYPTION_KEY or restore {_key_file()}.'
        )

    handle, temp_name = tempfile.mkstemp(prefix='nf-open-', suffix=path.suffix)
    os.close(handle)
    os.chmod(temp_name, 0o600)
    try:
        decrypt_file(path, temp_name, key)
        yield Path(temp_name)
    finally:
        try:
            os.unlink(temp_name)
        except OSError:
            pass
