"""
Evidence integrity layer.

Everything here exists to answer one question a defence counsel will ask:
"how do you know this file is the one you seized, and that nobody altered it?"

Field provenance is tagged in comments as:
  [STATUTORY]     required by Bharatiya Sakshya Adhiniyam 2023 s.63 or its Schedule
  [BNSS]          required by Bharatiya Nagarik Suraksha Sanhita 2023 s.193(3)
  [STANDARD]      derived from ISO/IEC 27037 or NIST SP 800-86
  [GOOD PRACTICE] our design choice, no legal backing claimed

The Part A / Part B split below is not our invention: it is THE SCHEDULE to the
BSA 2023, cross-referenced by s.63(4)(c) ("...in the certificate specified in
the Schedule"). See research/SPEC_01_EVIDENCE_INTEGRITY.md for verbatim text.
"""

import hashlib

from django.conf import settings
from django.db import models


# The Schedule prints these as checkboxes; we mirror the wording exactly so the
# generated certificate is the prescribed form rather than a paraphrase of it.
class DeviceType(models.TextChoices):
    COMPUTER = 'computer', 'Computer/Storage Media'
    DVR = 'dvr', 'DVR'
    MOBILE = 'mobile', 'Mobile'
    FLASH_DRIVE = 'flash', 'Flash Drive'
    CD_DVD = 'cd_dvd', 'CD/DVD'
    SERVER = 'server', 'Server'
    CLOUD = 'cloud', 'Cloud'
    OTHER = 'other', 'Other'


class HashAlgorithm(models.TextChoices):
    SHA256 = 'SHA256', 'SHA256'
    SHA1 = 'SHA1', 'SHA1'
    MD5 = 'MD5', 'MD5'
    OTHER = 'Other', 'Other (Legally acceptable standard)'


class Provenance(models.TextChoices):
    """
    What the file is, as distinct from what it contains.

    SEIZED is a declaration by an officer at intake. REFERENCE and SYNTHETIC
    are read from a sidecar manifest written by the tool that fetched or
    produced the file. UNATTESTED is the default and means exactly what it
    says — nobody has stated where this came from, so the system does not.
    """

    SEIZED = 'seized', 'Seized — captured from a network under investigation'
    REFERENCE = 'reference', 'Reference — real traffic from a published corpus'
    SYNTHETIC = 'synthetic', 'SYNTHETIC — generated by this tool, not evidence'
    UNATTESTED = 'unattested', 'Unattested — origin not declared'


class CustodianRelationship(models.TextChoices):
    OWNED = 'owned', 'Owned'
    MAINTAINED = 'maintained', 'Maintained'
    MANAGED = 'managed', 'Managed'
    OPERATED = 'operated', 'Operated'


def hash_file(path, algorithms=('sha256', 'sha1', 'md5'), chunk_size=1024 * 1024):
    """
    Hash a file in streaming chunks.

    All three digests are computed in a single pass, because re-reading a
    multi-gigabyte capture once per algorithm is wasteful and the marginal cost
    of a second and third hash over the same bytes is small.

    SHA-256 is the primary and the only one relied upon. SHA-1 and MD5 are
    computed because THE SCHEDULE prints a checkbox for each — a certificate
    that leaves two of the form's three named algorithms blank invites exactly
    the literal reading Gujarat courts have been applying to §63 certificates.
    Both are broken for collision resistance and neither is ever used alone;
    the certificate says so in as many words.
    """
    digests = {name: hashlib.new(name) for name in algorithms}
    size = 0
    with open(path, 'rb') as fh:
        while True:
            chunk = fh.read(chunk_size)
            if not chunk:
                break
            size += len(chunk)
            for d in digests.values():
                d.update(chunk)
    return {name: d.hexdigest() for name, d in digests.items()}, size


class Case(models.Model):
    """
    The investigation an exhibit belongs to.

    Why this is a table and not three text fields
    ---------------------------------------------
    Every exhibit used to carry its own free-text `case_reference`,
    `fir_number` and `police_station`. Twelve exhibits from one raid meant the
    same FIR number typed twelve times, and one of those twelve will be wrong.
    That is not a cosmetic defect: it is the discrepancy a defence counsel uses
    to ask which case the certificate actually refers to. ICJS names the
    principle for exactly this problem — "ONE DATA ONCE ENTRY".

    What this deliberately does NOT do
    ----------------------------------
    It does not rewrite the case reference already recorded on a sealed
    exhibit. Those fields stay authoritative for records sealed before this
    model existed, and linking a sealed exhibit to a Case is itself recorded as
    a custody event rather than applied silently. Editing an exhibit's stated
    provenance so that it matches newer software is altering the record to fit
    the tool.
    """

    class Status(models.TextChoices):
        # Aligned to the stages the BNSS actually names, not to a generic
        # workflow. "Closed" covers both a final report and an untraced case,
        # because the distinction is the magistrate's to record, not ours.
        REGISTERED = 'registered', 'FIR registered'
        INVESTIGATION = 'investigation', 'Under investigation'
        CHARGESHEETED = 'chargesheeted', 'Report filed under BNSS s.193'
        CLOSED = 'closed', 'Closed'

    case_number = models.CharField(max_length=60, unique=True)          # [GOOD PRACTICE]
    title = models.CharField(max_length=200)                            # [GOOD PRACTICE]

    # The identifiers a court will use to find this matter. Entered once here
    # and read from here by every exhibit, certificate and forwarding letter.
    fir_number = models.CharField(max_length=60, blank=True)            # [BNSS]
    police_station = models.CharField(max_length=200)                   # [BNSS]
    district = models.CharField(max_length=120, blank=True)             # [BNSS]
    # Free text on purpose. Sections get added and dropped during an
    # investigation, and a fixed list would be wrong within a year of the BNS
    # commencing.
    offence_sections = models.CharField(max_length=300, blank=True)     # [BNSS]

    status = models.CharField(
        max_length=16, choices=Status.choices, default=Status.REGISTERED,
    )
    opened_on = models.DateField()                                      # [BNSS]
    summary = models.TextField(blank=True)

    investigating_officer = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True,
        on_delete=models.SET_NULL, related_name='cases_as_io',
    )
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True,
        on_delete=models.SET_NULL, related_name='cases_created',
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-opened_on', '-id']

    def __str__(self):
        return f"{self.case_number} — {self.title}"

    @property
    def reference_line(self):
        """The one-line identifier a letter or certificate prints."""
        parts = [self.case_number]
        if self.fir_number:
            parts.append(f'FIR {self.fir_number}')
        if self.police_station:
            parts.append(self.police_station)
        return ' · '.join(parts)


class CaseAssignment(models.Model):
    """
    Who is on a case, and in what capacity.

    This is not the permission system — the API decides what a role may do.
    It answers a different question, the one the certificate needs: BSA 2023
    s.63(4) requires Part B to be signed by an expert, and the expert must be a
    different person from the officer who signed Part A. Recording both against
    the case is how that separation becomes checkable after the fact instead of
    being asserted at signing time.
    """

    class Role(models.TextChoices):
        IO = 'io', 'Investigating Officer'
        EXPERT = 'expert', 'FSL / Examiner'
        SUPERVISOR = 'supervisor', 'Supervising Officer'
        OBSERVER = 'observer', 'Observer (read-only)'

    case = models.ForeignKey(Case, on_delete=models.CASCADE, related_name='assignments')
    officer = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='case_assignments',
    )
    role = models.CharField(max_length=12, choices=Role.choices)
    assigned_at = models.DateTimeField(auto_now_add=True)
    assigned_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True,
        on_delete=models.SET_NULL, related_name='case_assignments_made',
    )

    class Meta:
        ordering = ['case', 'role', 'id']
        # One person, one capacity per case. Someone who is both the IO and the
        # countersigning expert defeats the point of s.63(4).
        unique_together = [('case', 'officer')]

    def __str__(self):
        return f"{self.officer} as {self.get_role_display()} on {self.case.case_number}"


class EvidenceRecord(models.Model):
    """
    The original seized artefact — for us, a PCAP file.

    Derived analysis (flows, detections) lives in the capture app and is
    explicitly NOT the evidence; it is opinion computed from the evidence.
    Keeping them in separate tables makes that distinction arguable in court
    rather than implied.
    """

    class Status(models.TextChoices):
        SEALED = 'sealed', 'Sealed — hash verified'
        TAMPERED = 'tampered', 'Integrity check FAILED'
        ARCHIVED = 'archived', 'Archived'

    Provenance = Provenance

    # Identity
    exhibit_number = models.CharField(max_length=100, unique=True)      # [GOOD PRACTICE]
    original_filename = models.CharField(max_length=255)                # [STANDARD]
    stored_path = models.CharField(max_length=500)                      # [GOOD PRACTICE]
    file_size_bytes = models.BigIntegerField(default=0)                 # [STANDARD]

    # Integrity — Schedule names SHA1/SHA256/MD5 explicitly
    sha256_hash = models.CharField(max_length=64, db_index=True)        # [STATUTORY]
    md5_hash = models.CharField(max_length=32, blank=True)              # [STATUTORY]
    # Printed because the Schedule names it, never relied upon: SHA-1 has
    # been collision-broken since SHAttered (2017).
    sha1_hash = models.CharField(max_length=40, blank=True)             # [STATUTORY]
    hash_algorithm_declared = models.CharField(                          # [STATUTORY]
        max_length=10, choices=HashAlgorithm.choices, default=HashAlgorithm.SHA256,
    )

    # Whether the sealed copy on disk is ciphertext. The recorded hashes above
    # are always of the plaintext capture, encrypted or not — see
    # evidence/crypto.py for why that is the only workable choice.
    encrypted_at_rest = models.BooleanField(default=False)              # [GOOD PRACTICE]
    encryption_algorithm = models.CharField(max_length=60, blank=True)  # [GOOD PRACTICE]

    status = models.CharField(max_length=12, choices=Status.choices, default=Status.SEALED)
    last_verified_at = models.DateTimeField(null=True, blank=True)      # [STANDARD]

    # Acquisition context — Schedule Part A device block
    acquisition_timestamp = models.DateTimeField()                       # [STATUTORY]
    device_type = models.CharField(                                      # [STATUTORY]
        max_length=12, choices=DeviceType.choices, default=DeviceType.COMPUTER,
    )
    device_make_model = models.CharField(max_length=200, blank=True)     # [STATUTORY]
    device_serial = models.CharField(max_length=120, blank=True)         # [STATUTORY]
    device_identifier = models.CharField(                                # [STATUTORY]
        max_length=200, blank=True,
        help_text='IMEI/UIN/UID/MAC/Cloud ID, as applicable',
    )
    custodian_relationship = models.CharField(                           # [STATUTORY]
        max_length=12, choices=CustodianRelationship.choices,
        default=CustodianRelationship.OPERATED,
    )

    # Case linkage
    # The case this exhibit belongs to. Nullable because exhibits sealed
    # before cases existed have only the text below, and backfilling them with
    # a guess would be worse than leaving the gap visible.
    case = models.ForeignKey(                                            # [BNSS]
        'Case', null=True, blank=True, on_delete=models.PROTECT,
        related_name='exhibits',
    )
    case_reference = models.CharField(max_length=120, blank=True)        # [GOOD PRACTICE]

    # The FIR the exhibit belongs to, and the station holding it.
    #
    # `case_reference` was the only case linkage and it is free text, which is
    # fine for a working label and useless for anything that has to match a
    # register. Gujarat's Cyber Financial Fraud e-Zero FIR service (launched
    # 27 July 2026) generates an FIR directly from a 1930-helpline complaint,
    # so an exhibit arriving at a district station already has a number to be
    # filed against.
    #
    # Deliberately NOT format-validated. FIR numbering differs by state and by
    # station, and rejecting a number because it does not match a pattern we
    # invented would be worse than accepting what the officer typed. It is
    # stored as given, labelled, and printed on the certificate where a court
    # can check it against the register.
    fir_number = models.CharField(max_length=60, blank=True)             # [GOOD PRACTICE]
    police_station = models.CharField(max_length=200, blank=True)        # [GOOD PRACTICE]

    seized_from = models.CharField(max_length=200, blank=True)           # [STANDARD]
    acquisition_notes = models.TextField(blank=True)                     # [STANDARD]

    # Where the bytes came from.
    #
    # A generated capture and a seized one are byte-for-byte indistinguishable,
    # so without this a Section 63 certificate printed over demo traffic looks
    # exactly like one printed over evidence. The value is set from the
    # sidecar manifest written by whatever produced or fetched the file
    # (capture/provenance.py), or declared by the officer at intake.
    #
    # The default is UNATTESTED and not SEIZED on purpose: a file arriving with
    # no statement about its origin has not thereby been shown to be real.
    provenance = models.CharField(                                       # [GOOD PRACTICE]
        max_length=12, choices=Provenance.choices, default=Provenance.UNATTESTED,
    )
    provenance_detail = models.TextField(blank=True)                     # [GOOD PRACTICE]

    collected_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True,
        on_delete=models.SET_NULL, related_name='collected_evidence',
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.exhibit_number} · {self.original_filename}"

    @property
    def is_demonstration_only(self):
        """
        True when this exhibit is traffic we generated.

        Everything that renders an exhibit — the register, the custody view,
        the Section 63 PDF — asks this and says so plainly when it is true.
        A demonstration certificate that looks like a real one is the failure
        mode this whole field exists to prevent.
        """
        return self.provenance == Provenance.SYNTHETIC

    def verify(self):
        """
        Recompute the digest and compare against the sealed value.

        Returns (ok, computed_sha256). A mismatch flips status to TAMPERED and
        is deliberately sticky — an artefact that ever failed verification
        should not silently return to 'sealed' on a later pass.
        """
        from django.utils import timezone

        from .crypto import EvidenceDecryptionError, readable

        try:
            # Decrypts first when the store is encrypted, so `computed` is
            # always a digest of the capture as seized and stays comparable to
            # the value printed on the certificate.
            with readable(self.stored_path) as plaintext:
                digests, _ = hash_file(plaintext, algorithms=('sha256',))
        except (OSError, EvidenceDecryptionError):
            # A file that will not decrypt is indistinguishable, from here,
            # from one that has been altered — and both answers are the same
            # answer: do not trust this artefact.
            self.status = self.Status.TAMPERED
            self.save(update_fields=['status'])
            return False, None

        computed = digests['sha256']
        ok = (computed == self.sha256_hash)
        self.last_verified_at = timezone.now()
        if not ok:
            self.status = self.Status.TAMPERED
        self.save(update_fields=['last_verified_at', 'status'])
        return ok, computed


class CustodyEvent(models.Model):
    """
    One link in the chain of custody, hash-chained to its predecessor.

    Each row stores the digest of the previous row, so removing or editing a
    past entry breaks every subsequent link. This is a tamper-*evident* log,
    not tamper-proof — it detects alteration rather than preventing it, which
    is the honest claim to make about a database table.
    """

    class Action(models.TextChoices):
        ACQUIRED = 'acquired', 'Acquired / Seized'
        HASHED = 'hashed', 'Hash computed'
        VERIFIED = 'verified', 'Integrity verified'
        ANALYSED = 'analysed', 'Analysed'
        VIEWED = 'viewed', 'Viewed'
        EXPORTED = 'exported', 'Exported'
        TRANSFERRED = 'transferred', 'Custody transferred'
        CERTIFICATE_ISSUED = 'certificate', 'Section 63 certificate issued'
        # Part B is a distinct act by a distinct person, so it gets its own
        # action. Reusing CERTIFICATE_ISSUED printed two identical rows on the
        # custody annexure and hid who actually countersigned.
        PART_B_SIGNED = 'part_b_signed', 'Section 63 Part B countersigned by expert'
        # Attaching a sealed exhibit to a case changes what the record says
        # about it, so it is a movement in the chain and not a silent edit.
        CASE_LINKED = 'case_linked', 'Linked to case'
        # Encrypting the store rewrites the bytes on disk without changing the
        # evidence. That distinction is exactly the kind a defence counsel
        # probes, so the act is logged and the log says the hash is unchanged.
        ENCRYPTED = 'encrypted', 'Encrypted at rest'

    evidence = models.ForeignKey(
        EvidenceRecord, on_delete=models.CASCADE, related_name='custody_events',
    )
    sequence = models.PositiveIntegerField()
    action = models.CharField(max_length=16, choices=Action.choices)

    actor = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True,
        on_delete=models.SET_NULL, related_name='custody_events',
    )
    actor_badge = models.CharField(max_length=50, blank=True)
    actor_ip = models.GenericIPAddressField(null=True, blank=True)

    detail = models.TextField(blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    previous_hash = models.CharField(max_length=64, blank=True)
    entry_hash = models.CharField(max_length=64, blank=True)

    class Meta:
        ordering = ['evidence', 'sequence']
        unique_together = [('evidence', 'sequence')]

    def __str__(self):
        return f"#{self.sequence} {self.action} · {self.evidence.exhibit_number}"

    def compute_hash(self):
        """Digest over the immutable content of this entry plus the prior link."""
        payload = '|'.join([
            str(self.evidence_id),
            str(self.sequence),
            self.action,
            str(self.actor_badge or ''),
            str(self.actor_ip or ''),
            self.detail or '',
            self.timestamp.isoformat() if self.timestamp else '',
            self.previous_hash or '',
        ])
        return hashlib.sha256(payload.encode('utf-8')).hexdigest()


class Section63Certificate(models.Model):
    """
    A generated certificate under BSA 2023 s.63(4)(c), following THE SCHEDULE.

    Part A is signed by the person in charge of the device; Part B by an
    expert. The statute requires both ("...signed by a person in charge ...
    and an expert"), so a certificate with only one part is incomplete and is
    marked as such rather than being presented as valid.
    """

    evidence = models.ForeignKey(
        EvidenceRecord, on_delete=models.CASCADE, related_name='certificates',
    )
    session = models.ForeignKey(
        'capture.CaptureSession', null=True, blank=True,
        on_delete=models.SET_NULL, related_name='certificates',
    )
    reference = models.CharField(max_length=100, unique=True)

    # ── Part A — person in charge of the device / activities ──
    part_a_name = models.CharField(max_length=200, blank=True)
    part_a_designation = models.CharField(max_length=200, blank=True)
    part_a_organisation = models.CharField(max_length=200, blank=True)
    part_a_address = models.TextField(blank=True)
    part_a_relationship = models.CharField(
        max_length=12, choices=CustodianRelationship.choices,
        default=CustodianRelationship.OPERATED,
    )
    part_a_signed_at = models.DateTimeField(null=True, blank=True)
    part_a_user = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True,
        on_delete=models.SET_NULL, related_name='part_a_certificates',
    )

    # ── Part B — expert ──
    part_b_name = models.CharField(max_length=200, blank=True)
    part_b_designation = models.CharField(max_length=200, blank=True)
    part_b_organisation = models.CharField(max_length=200, blank=True)
    part_b_qualification = models.CharField(
        max_length=300, blank=True,
        help_text="s.63 does not define 'expert'; qualification is recorded "
                  "so the court can assess competence.",
    )
    part_b_signed_at = models.DateTimeField(null=True, blank=True)
    part_b_user = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True,
        on_delete=models.SET_NULL, related_name='part_b_certificates',
    )

    # Snapshot of the facts certified, frozen at issue time
    certified_sha256 = models.CharField(max_length=64)
    certified_md5 = models.CharField(max_length=32, blank=True)
    certified_sha1 = models.CharField(max_length=40, blank=True)
    certified_algorithm = models.CharField(
        max_length=10, choices=HashAlgorithm.choices, default=HashAlgorithm.SHA256,
    )
    device_description = models.TextField(blank=True)
    findings_summary = models.TextField(blank=True)

    generated_at = models.DateTimeField(auto_now_add=True)
    pdf_path = models.CharField(max_length=500, blank=True)

    class Meta:
        ordering = ['-generated_at']

    def __str__(self):
        return f"{self.reference} · {self.evidence.exhibit_number}"

    @property
    def is_complete(self):
        """Both parts signed, as s.63(4) requires conjunctively."""
        return bool(self.part_a_signed_at and self.part_b_signed_at)
